
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 23 2026 13:40:09 IST (Feb 23 2026 08:10:09 UTC)

// Verification Directory fv/four_bit_adder 

module four_bit_adder(a, b, c0, s, c4);
  input [3:0] a, b;
  input c0;
  output [3:0] s, c4;
  wire [3:0] a, b;
  wire c0;
  wire [3:0] s, c4;
  wire n_0, n_2, n_4;
  assign c4[1] = 1'b0;
  assign c4[2] = 1'b0;
  assign c4[3] = 1'b0;
  ADDFX2 g242__2398(.A (b[3]), .B (a[3]), .CI (n_4), .CO (c4[0]), .S
       (s[3]));
  ADDFX2 g243__5107(.A (b[2]), .B (a[2]), .CI (n_2), .CO (n_4), .S
       (s[2]));
  ADDFX2 g244__6260(.A (b[1]), .B (a[1]), .CI (n_0), .CO (n_2), .S
       (s[1]));
  ADDFX2 g245__4319(.A (a[0]), .B (c0), .CI (b[0]), .CO (n_0), .S
       (s[0]));
endmodule

